2021-05-23 13:31:48,701 INFO    MainThread:22836 [wandb_setup.py:_flush():69] setting env: {}
2021-05-23 13:31:48,701 INFO    MainThread:22836 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-23 13:31:48,701 INFO    MainThread:22836 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210523_133148-t3wjp0k1\logs\debug.log
2021-05-23 13:31:48,701 INFO    MainThread:22836 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210523_133148-t3wjp0k1\logs\debug-internal.log
2021-05-23 13:31:48,701 INFO    MainThread:22836 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000206AA644640>
2021-05-23 13:31:48,702 INFO    MainThread:22836 [wandb_init.py:init():369] calling init triggers
2021-05-23 13:31:48,702 INFO    MainThread:22836 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-23 13:31:48,702 INFO    MainThread:22836 [wandb_init.py:init():418] starting backend
2021-05-23 13:31:48,702 INFO    MainThread:22836 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-05-23 13:31:48,705 INFO    MainThread:22836 [backend.py:ensure_launched():132] starting backend process...
2021-05-23 13:31:48,761 INFO    MainThread:22836 [backend.py:ensure_launched():136] started backend process with pid: 1312
2021-05-23 13:31:48,762 INFO    MainThread:22836 [wandb_init.py:init():423] backend started and connected
2021-05-23 13:31:48,806 INFO    MainThread:22836 [wandb_init.py:init():465] updated telemetry
2021-05-23 13:31:48,807 INFO    MainThread:22836 [wandb_init.py:init():484] communicating current version
2021-05-23 13:31:50,124 INFO    MainThread:22836 [wandb_init.py:init():489] got version response 
2021-05-23 13:31:50,124 INFO    MainThread:22836 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-23 13:31:50,496 INFO    MainThread:22836 [wandb_init.py:init():522] starting run threads in backend
2021-05-23 13:31:55,501 WARNING MainThread:22836 [wandb_init.py:init():764] interrupted
Traceback (most recent call last):
  File "C:\Users\cdami\Anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 744, in init
    run = wi.init()
  File "C:\Users\cdami\Anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 525, in init
    _ = backend.interface.communicate_run_start(run_obj)
  File "C:\Users\cdami\Anaconda3\lib\site-packages\wandb\sdk\interface\interface.py", line 799, in communicate_run_start
    result = self._communicate(rec)
  File "C:\Users\cdami\Anaconda3\lib\site-packages\wandb\sdk\interface\interface.py", line 537, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\cdami\Anaconda3\lib\site-packages\wandb\sdk\interface\interface.py", line 82, in get
    is_set = self._object_ready.wait(timeout)
  File "C:\Users\cdami\Anaconda3\lib\threading.py", line 558, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Users\cdami\Anaconda3\lib\threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
