2021-05-22 21:35:17,947 INFO    MainThread:8612 [wandb_setup.py:_flush():69] setting env: {}
2021-05-22 21:35:17,947 INFO    MainThread:8612 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-22 21:35:17,947 INFO    MainThread:8612 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '849f3acb879e58646f94244a57a6323b393471d0'}
2021-05-22 21:35:17,947 INFO    MainThread:8612 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210522_213517-6o7zyke1\logs\debug.log
2021-05-22 21:35:17,948 INFO    MainThread:8612 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210522_213517-6o7zyke1\logs\debug-internal.log
2021-05-22 21:35:17,948 INFO    MainThread:8612 [wandb_init.py:init():369] calling init triggers
2021-05-22 21:35:17,948 INFO    MainThread:8612 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-22 21:35:17,948 INFO    MainThread:8612 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 34uyr7fz
2021-05-22 21:35:17,950 INFO    MainThread:8612 [wandb_run.py:finish():1208] finishing run coinitialized/anomaly/34uyr7fz
2021-05-22 21:35:17,964 INFO    MainThread:8612 [jupyter.py:save_history():320] not saving jupyter history
2021-05-22 21:35:17,964 INFO    MainThread:8612 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-22 21:35:17,964 INFO    MainThread:8612 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-22 21:35:17,964 INFO    MainThread:8612 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-22 21:35:17,966 INFO    MainThread:8612 [wandb_run.py:_restore():1507] restore
2021-05-22 21:35:17,975 INFO    MainThread:8612 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1236
  total_bytes: 1236
}

2021-05-22 21:35:18,323 INFO    MainThread:8612 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1236
  total_bytes: 1236
}

2021-05-22 21:35:18,999 INFO    MainThread:8612 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1236
  total_bytes: 18058
}

2021-05-22 21:35:19,366 INFO    MainThread:8612 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 18060
  total_bytes: 18060
}

2021-05-22 21:35:19,480 INFO    MainThread:8612 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 18060
  total_bytes: 18060
}

2021-05-22 21:35:19,589 INFO    MainThread:8612 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 18060
  total_bytes: 18060
}

2021-05-22 21:35:19,699 INFO    MainThread:8612 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 18060
  total_bytes: 18060
}

2021-05-22 21:35:19,807 INFO    MainThread:8612 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 18060
  total_bytes: 18060
}

2021-05-22 21:35:19,917 INFO    MainThread:8612 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 18060
  total_bytes: 18060
}

2021-05-22 21:35:21,034 INFO    MainThread:8612 [wandb_run.py:_show_files():1879] logging synced files
2021-05-22 21:35:21,040 INFO    MainThread:8612 [wandb_init.py:init():418] starting backend
2021-05-22 21:35:21,040 INFO    MainThread:8612 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-05-22 21:35:21,044 INFO    MainThread:8612 [backend.py:ensure_launched():132] starting backend process...
2021-05-22 21:35:21,108 INFO    MainThread:8612 [backend.py:ensure_launched():136] started backend process with pid: 24548
2021-05-22 21:35:21,109 INFO    MainThread:8612 [wandb_init.py:init():423] backend started and connected
2021-05-22 21:35:21,120 INFO    MainThread:8612 [wandb_init.py:init():465] updated telemetry
2021-05-22 21:35:21,121 INFO    MainThread:8612 [wandb_init.py:init():484] communicating current version
2021-05-22 21:35:22,326 INFO    MainThread:8612 [wandb_init.py:init():489] got version response 
2021-05-22 21:35:22,326 INFO    MainThread:8612 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-22 21:35:22,729 INFO    MainThread:8612 [wandb_init.py:init():522] starting run threads in backend
2021-05-22 21:35:27,738 INFO    MainThread:8612 [wandb_run.py:_console_start():1565] atexit reg
2021-05-22 21:35:27,739 INFO    MainThread:8612 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-22 21:35:27,739 INFO    MainThread:8612 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-22 21:35:27,739 INFO    MainThread:8612 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-22 21:35:27,739 INFO    MainThread:8612 [wandb_init.py:init():546] run started, returning control to user process
