2021-05-23 20:49:50,037 INFO    MainThread:31840 [wandb_setup.py:_flush():69] setting env: {}
2021-05-23 20:49:50,038 INFO    MainThread:31840 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-23 20:49:50,038 INFO    MainThread:31840 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210523_204950-3dpzcs0s\logs\debug.log
2021-05-23 20:49:50,038 INFO    MainThread:31840 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210523_204950-3dpzcs0s\logs\debug-internal.log
2021-05-23 20:49:50,039 INFO    MainThread:31840 [wandb_init.py:init():369] calling init triggers
2021-05-23 20:49:50,039 INFO    MainThread:31840 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-23 20:49:50,039 INFO    MainThread:31840 [wandb_init.py:init():389] re-initializing run, found existing run on stack: x3lkhimw
2021-05-23 20:49:50,041 INFO    MainThread:31840 [wandb_run.py:finish():1208] finishing run coinitialized/anomaly/x3lkhimw
2021-05-23 20:49:50,186 INFO    MainThread:31840 [jupyter.py:save_history():320] not saving jupyter history
2021-05-23 20:49:50,186 INFO    MainThread:31840 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-05-23 20:49:50,186 INFO    MainThread:31840 [wandb_init.py:_jupyter_teardown():268] cleaning up jupyter logic
2021-05-23 20:49:50,186 INFO    MainThread:31840 [wandb_run.py:_atexit_cleanup():1535] got exitcode: 0
2021-05-23 20:49:50,187 INFO    MainThread:31840 [wandb_run.py:_restore():1507] restore
2021-05-23 20:49:50,193 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1237
  total_bytes: 1237
}

2021-05-23 20:49:50,503 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1237
  total_bytes: 1237
}

2021-05-23 20:49:51,432 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1237
  total_bytes: 17917
}

2021-05-23 20:49:51,906 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1237
  total_bytes: 17919
}

2021-05-23 20:49:52,017 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1237
  total_bytes: 17919
}

2021-05-23 20:49:52,125 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1237
  total_bytes: 17919
}

2021-05-23 20:49:52,233 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 1237
  total_bytes: 17919
}

2021-05-23 20:49:52,343 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17919
  total_bytes: 17919
}

2021-05-23 20:49:52,451 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17919
  total_bytes: 17919
}

2021-05-23 20:49:52,560 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17919
  total_bytes: 17919
}

2021-05-23 20:49:52,669 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17919
  total_bytes: 17919
}

2021-05-23 20:49:52,778 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17919
  total_bytes: 17919
}

2021-05-23 20:49:52,888 INFO    MainThread:31840 [wandb_run.py:_wait_for_finish():1657] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 17919
  total_bytes: 17919
}

2021-05-23 20:49:54,072 INFO    MainThread:31840 [wandb_run.py:_show_files():1879] logging synced files
2021-05-23 20:49:54,079 INFO    MainThread:31840 [wandb_init.py:init():418] starting backend
2021-05-23 20:49:54,079 INFO    MainThread:31840 [backend.py:_multiprocessing_setup():70] multiprocessing start_methods=spawn, using: spawn
2021-05-23 20:49:54,082 INFO    MainThread:31840 [backend.py:ensure_launched():132] starting backend process...
2021-05-23 20:49:54,150 INFO    MainThread:31840 [backend.py:ensure_launched():136] started backend process with pid: 29512
2021-05-23 20:49:54,159 INFO    MainThread:31840 [wandb_init.py:init():423] backend started and connected
2021-05-23 20:49:54,170 INFO    MainThread:31840 [wandb_init.py:init():465] updated telemetry
2021-05-23 20:49:54,171 INFO    MainThread:31840 [wandb_init.py:init():484] communicating current version
2021-05-23 20:49:55,804 INFO    MainThread:31840 [wandb_init.py:init():489] got version response 
2021-05-23 20:49:55,804 INFO    MainThread:31840 [wandb_init.py:init():497] communicating run to backend with 30 second timeout
2021-05-23 20:49:56,156 INFO    MainThread:31840 [wandb_init.py:init():522] starting run threads in backend
2021-05-23 20:50:01,197 INFO    MainThread:31840 [wandb_run.py:_console_start():1565] atexit reg
2021-05-23 20:50:01,198 INFO    MainThread:31840 [wandb_run.py:_redirect():1412] redirect: SettingsConsole.WRAP
2021-05-23 20:50:01,199 INFO    MainThread:31840 [wandb_run.py:_redirect():1455] Wrapping output streams.
2021-05-23 20:50:01,199 INFO    MainThread:31840 [wandb_run.py:_redirect():1479] Redirects installed.
2021-05-23 20:50:01,199 INFO    MainThread:31840 [wandb_init.py:init():546] run started, returning control to user process
2021-05-23 21:06:45,061 INFO    MainThread:31840 [wandb_setup.py:_flush():69] setting env: {}
2021-05-23 21:06:45,062 INFO    MainThread:31840 [wandb_setup.py:_flush():69] setting login settings: {}
2021-05-23 21:06:45,062 INFO    MainThread:31840 [wandb_init.py:_log_setup():336] Logging user logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210523_210645-3m4syy7t\logs\debug.log
2021-05-23 21:06:45,062 INFO    MainThread:31840 [wandb_init.py:_log_setup():337] Logging internal logs to c:\Users\cdami\Documents\Python Scripts\Spatiotemporal-Autoencoder-Anomaly-Detection\wandb\run-20210523_210645-3m4syy7t\logs\debug-internal.log
2021-05-23 21:06:45,063 INFO    MainThread:31840 [wandb_init.py:_jupyter_setup():287] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000238BB920820>
2021-05-23 21:06:45,063 INFO    MainThread:31840 [wandb_init.py:init():369] calling init triggers
2021-05-23 21:06:45,063 INFO    MainThread:31840 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {}
2021-05-23 21:06:45,063 INFO    MainThread:31840 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 3dpzcs0s
2021-05-23 21:06:45,065 INFO    MainThread:31840 [wandb_run.py:finish():1208] finishing run coinitialized/anomaly/3dpzcs0s
